name: Build Python and Test Python App

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - name: Run tests with unittest
        env: 
          DB_CONNECTION: ${{ secrets.TEST_DB_CONNECTION }}
          AUTH_REQUEST_DATA: ${{ secrets.TEST_AUTH_REQUEST_DATA }}
        run: |
          python -m unittest api/tests/attendee_test.py
          python -m unittest api/tests/event_test.py
          python -m unittest api/tests/group_test.py
      
